name: Sync Issue Templates

on:
  push:
    branches:
      - master
    paths:
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .github repo
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: sync issue templates
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          REPOS=("porotech-documentation" "porotech-frontend" "porotech-backend" "porotech-embedded" "porotech-client")
          for REPO in "${REPOS[@]}"; do
            echo "Synching to $REPO..."
            git clone --depth 1 https://x-access-token:${GH_TOKEN}@github.com/PoroTech-Industries/$REPO.git
            mkdir -p $REPO/.github
            cp -r .github/ISSUE_TEMPLATE $REPO/.github/
            cd $REPO

            if [-z "$(git branch -a)" ]; then
              echo "# $REPO" > README.md
              git add README.md
              git commit -m "Initial commit"
              git branch -M master
              git push -u origin master
            else
              default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
              if [ -z "$default_branch" ]; then
                echo "Could not determine default branch for $REPO. Assuming 'master'."
                default_branch="master"
              fi
              echo "Default branch for $REPO is $default_branch"
            fi
            
            branch_name="enhancement/update-issue-templates-${{ github.run_id }}"
            git checkout -b "$branch_name"
            git add .github/ISSUE_TEMPLATE
            if git diff --cached --quiet; then
              echo "No changes to commit for $REPO"
            else
              git commit -m "Syncing Issue Templates"
              git push origin "$branch_name"
              gh pr create --base "$main_branch" --head "$branch_name" --title "Sync issue Templates" --body "This PR syncs issue templates as specified through latest push to master on \"https://github.com/PoroTech-Industries/.github\""
            fi
            cd .. 
            rm -rf $REPO
          done
